### ISSUE TITLE
Trying to find a way to override the title of flash message with custom message

### ISSUE THREAD

**Issue by Shivam0609** [wiltonsr/Flask-Toastr#14]
**Current Behaviour :**
Getting category displayed on flash message like Info, Success, Warning, Message  etc..

![image](https://user-images.githubusercontent.com/27969092/186192962-f1bf5328-d5de-4577-b26b-7b72ce94ab96.png)

**Required Behaviour :**
Instead of Category want to see a Custom message as below.

![image](https://user-images.githubusercontent.com/27969092/186193237-e2a55427-4175-4ca7-8f18-9eb807ee3bae.png)

If their is some configuration paramter to do that please confirm ?

**Comment by Shivam0609** [comment]
Seems like it is not supported as of now

**Comment by Shivam0609** [comment]
Just need this minor change

```python
message = Template('''
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <script type="text/javascript">
      (function($) {
        $(document).ready(function() {
          {{ toastr_options }}
          {% for category, message in messages %}
            {% if category is undefined or category == 'message' %}
              toastr.info(\'{{ message | replace("'","\\\\'") }}\', \'{{ category|capitalize }}\')
            {% elif category and category not in ['message', 'error', 'warning', 'info', 'success']  %}
              toastr.info(\'{{ message | replace("'","\\\\'") }}\', \'{{ category|capitalize }}\')
            {% else %}
              toastr.{{ category }}(\'{{ message | replace("'","\\\\'") }}\', \'{{ category|capitalize }}\')
            {% endif %}
          {% endfor %}
        });
      })(jQuery);
    </script>
  {% endif %}
{% endwith %}
''')
```

And to invoke

```python
flash("All OK","test header")
```

**Comment by wiltonsr** [comment]
Hi, @Shivam0609 

Thanks for the interest in `Flask-Toastr`.

You are right, for now, `Flask-Toastr` doesn't support custom titles.

> Just need this minor change
> 
> ```python
> message = Template('''
> {% with messages = get_flashed_messages(with_categories=true) %}
>   {% if messages %}
>     <script type="text/javascript">
>       (function($) {
>         $(document).ready(function() {
>           {{ toastr_options }}
>           {% for category, message in messages %}
>             {% if category is undefined or category == 'message' %}
>               toastr.info(\'{{ message | replace("'","\\\\'") }}\', \'{{ category|capitalize }}\')
>             {% elif category and category not in ['message', 'error', 'warning', 'info', 'success']  %}
>               toastr.info(\'{{ message | replace("'","\\\\'") }}\', \'{{ category|capitalize }}\')
>             {% else %}
>               toastr.{{ category }}(\'{{ message | replace("'","\\\\'") }}\', \'{{ category|capitalize }}\')
>             {% endif %}
>           {% endfor %}
>         });
>       })(jQuery);
>     </script>
>   {% endif %}
> {% endwith %}
> ''')
> ```
> 
> And to invoke
> 
> ```python
> flash("All OK","test header")
> ```

This way all messages will be categorized as `info`.

I was thinking about:

```python
flash({'title': "Custom Title", 'message': "All OK"}, 'success')
```

And check if is a mapping:

```python
{% with messages = get_flashed_messages(with_categories=true) %}                
  {% if messages %}                                                             
    <script type="text/javascript">                                             
      (function($) {                                                            
        $(document).ready(function() {                                          
          {{ toastr_options }}                                                  
          {% for category, message in messages %}                               
            {% if category is undefined or category == 'message' %}             
              {% set category = 'info' %}                                       
            {% endif %}                                                         
            {% if message is mapping %}                                                                                                                           
              toastr.{{ category }}(\'{{ message['message'] | replace("'","\\\\'") }}\', \'{{ message['title'] | replace("'","\\\\'") }}\')
            {% else %}                                                          
              toastr.{{ category }}(\'{{ message | replace("'","\\\\'") }}\', \'{{ category|capitalize }}\')
            {% endif %}                                                         
          {% endfor %}                                                          
        });                                                                     
      })(jQuery);                                                               
    </script>                                                                   
  {% endif %}                                                                   
{% endwith %} 
```

**Comment by Shivam0609** [comment]
Above solutions looks Fine to me aswell and is more general

**Comment by Shivam0609** [comment]
Hi @wiltonsr , 

Hope to get this implemented soon, That will be Great.

Thanks

**Comment by wiltonsr** [comment]
@Shivam0609 

Version [0.5.8](https://pypi.org/project/Flask-Toastr/0.5.8/) already available.

I used your solution and mine, so you could use:

```python
@app.route('/')
def index():
    flash("Message", 'Custom Title') # Will be info category by default
    flash({'title': "Custom Title", 'message': "Info Category"}) # Will also be info category by default
    flash({'title': "Custom Title", 'message': "Error Message"}, 'error') # Or use dict syntax to pass a custom category
    return render_template('index.html')
```
