### ISSUE TITLE
The icon resolution issue

### ISSUE THREAD

**Issue by zzh8241102** [wiltonsr/Flask-Toastr#16]
Thanks to all these great works achieved by you guys, It's amazingly great and convenient! 
However, the resolution of the messaging icon and font is not good as excepted, 
It will be great if you guys can alternate the icon with a clear and modern svg icon which will not add explicit overhead,
or give the users a interface to change the icon and font, as well as obey the concise and powerful style of this software.
cheers!🚀

**Comment by wiltonsr** [comment]
Hello, @zzh8241102 

Sorry for the huge delay in responding.

You can change Toastr's icon using only `CSS` with `FontAwesome`.

In [their repository](https://github.com/CodeSeven/toastr) there is a [link to a demo](https://plnkr.co/edit/6W9URNyyp2ItO4aUWzBB?p=preview&preview) doing that.
