### ISSUE TITLE
Add support for animation options and auto-hiding

### ISSUE THREAD

**Issue by tvb** [wiltonsr/Flask-Toastr#5]
See https://github.com/CodeSeven/toastr#animation-options and https://github.com/CodeSeven/toastr#prevent-from-auto-hiding

Thanks!

**Comment by tvb** [comment]
@wiltonsr do you got the time to implement this?

**Comment by wiltonsr** [comment]
Hi @tvb.

Sorry, i have been bogged down with other work projects and i haven't had time to continue this yet.

**Comment by tvb** [comment]
Not a problem!

**Comment by wiltonsr** [comment]
@tvb to prevent `Auto Hiding` just set

`TOASTR_TIMEOUT` and `TOASTR_EXTENDED_TIMEOUT` to `0` as in the link you mentioned.

**Comment by wiltonsr** [comment]
@tvb Support for animation options added in [`v0.5.6`](https://pypi.org/project/Flask-Toastr/0.5.6/).
